name: object-locator
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0=mkl
  - absl-py=0.7.1=py37_0
  - astor=0.7.1=py37_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h1de35cc_1
  - ca-certificates=2019.1.23=0
  - certifi=2019.3.9=py37_0
  - gast=0.2.2=py37_0
  - grpcio=1.16.1=py37h044775b_1
  - h5py=2.9.0=py37h3134771_0
  - hdf5=1.10.4=hfa1e0ec_0
  - intel-openmp=2019.3=199
  - keras-applications=1.0.7=py_0
  - keras-preprocessing=1.0.9=py_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libprotobuf=3.6.1=hd9629dc_0
  - markdown=3.1=py37_0
  - mkl=2019.3=199
  - mkl_fft=1.0.10=py37h5e564d8_0
  - mkl_random=1.0.2=py37h27c97d8_0
  - mock=2.0.0=py37_0
  - ncurses=6.1=h0a44026_1
  - numpy=1.16.3=py37hacdab7b_0
  - numpy-base=1.16.3=py37h6575580_0
  - openssl=1.1.1b=h1de35cc_1
  - pbr=5.1.3=py_0
  - pip=19.1=py37_0
  - protobuf=3.6.1=py37h0a44026_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - scikit-learn=0.20.3=py37h27c97d8_0
  - scipy=1.2.1=py37h1410ff5_0
  - setuptools=41.0.0=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.28.0=ha441bb4_0
  - tensorboard=1.13.1=py37haf313ee_0
  - tensorflow=1.13.1=mkl_py37h70c3834_0
  - tensorflow-base=1.13.1=mkl_py37h66b1bf0_0
  - tensorflow-estimator=1.13.0=py_0
  - termcolor=1.1.0=py37_1
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.15.2=py_0
  - wheel=0.33.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - appnope==0.1.0
    - backcall==0.1.0
    - decorator==4.4.0
    - ipdb==0.12
    - ipython==7.5.0
    - ipython-genutils==0.2.0
    - jedi==0.13.3
    - opencv-python==4.1.0.25
    - pandas==0.24.2
    - parso==0.4.0
    - pexpect==4.7.0
    - pickleshare==0.7.5
    - prompt-toolkit==2.0.9
    - ptyprocess==0.6.0
    - pygments==2.3.1
    - python-dateutil==2.8.0
    - pytz==2019.1
    - tqdm==4.31.1
    - traitlets==4.3.2
    - wcwidth==0.1.7
prefix: /Users/bi/miniconda3/envs/object-locator

